<a href="https://colab.research.google.com/github/yyred-max/Analisis_Data_Eksploratif/blob/main/PERTEMUAN_1___YULIANA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LATIHAN PERTEMUAN 1

In [ ]:
# MEMBUAT MATRIKS 1 D
import numpy as np
A = np.array([0,0,1])
print("Matriks 1 Dimensi =", A)

Matriks 1 Dimensi = [0 0 1]


In [ ]:
# MATRIK 2 D
B=np.array([[0,0,1],[1,1,2]])
B

array([[0, 0, 1],
       [1, 1, 2]])

In [ ]:
# MATRIKS SATUAN
SATU=np.ones((10,10))
# MATRIK NOL
NOL=np.zeros((5,5))
# MATRIKS RANDOM
RANDOM=np.random.random((7,7,))
print("Matriks satuan=", SATU)
print("Matriks nol=", NOL)
print("Matrik Random=", RANDOM)

Matriks satuan= [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Matriks nol= [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matrik Random= [[0.71116897 0.38942545 0.71637654 0.62185566 0.35171101 0.87100887
  0.61117541]
 [0.53549737 0.17431626 0.52854341 0.65413714 0.61188943 0.96992267
  0.80004712]
 [0.09611366 0.75303428 0.78322176 0.85479685 0.08260723 0.47662465
  0.31203654]
 [0.00173918 0.89687095 0.29719879 0.81970653 0.70037101 0.43285498
  0.47419078]
 [0.55540834 0.99877402 0.128847   0.98476181 0.54744543 0.90970304
  0.56336586]
 [0.14530038 0.80357991 0.4012973  0.01640962 0.75419442 0.01878386
  0.04127874]
 [0.55056649 0.10379465 0.70102061 0.38175

In [ ]:
# MATRIKS KOSONG
Kosong=np.empty((2,2))
print("Matriks kosong=", Kosong)
# MATRIKS [5,10,15,....,100]
X=np.arange(5,105,5)
print("Matriks baru=", X)
# MATRIK DENGAN ELEMEN 0 - 1 SEBANYAK 10
Y=np.linspace(0,1,10)
print("Matriks Y=", Y)

Matriks kosong= [[2.23022951e-315 0.00000000e+000]
 [1.65515672e-312 3.95252517e-322]]
Matriks baru= [  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]
Matriks Y= [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# OPERASI MATRIKS
p=np.array([[0,0,1],[1,1,0]])
q=np.array([[1,0,0],[1,1,1]])
# PENJUMLAHAN
J=np.add(p,q)
# PENGURANGAN
K=np.subtract(p.q)
print("p+q=", J)
print("p-q=", K)


In [ ]:
# BUATLAH MATRIKS BERUKURAN 2X2
A=np.array([[4,8],[8,16]])
B=np.array([[2,2],[4,4]])

# PERKALIAN AXB, np.multiply
AXB=np.multiply(A,B)

# PEMBAGIAN A:B, np.divide
AbagiB=np.divide(A,B)

# MENGHITUNG SISA BAGI
Sisa_Bagi=np.remainder(A,B)

print("AXB=", AXB)
print("A:B=", AbagiB)
print("Sisa hasil bagi=", Sisa_Bagi)




AXB= [[ 8 16]
 [32 64]]
A:B= [[2. 4.]
 [2. 4.]]
Sisa hasil bagi= [[0 0]
 [0 0]]


In [ ]:
# MEMBUAT DATA FRAME
import pandas as pd
KOLOM=['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15'] #diambil dari data frame, jumlah kalimat yang dipisahkan tanda koma
DATA=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data', names=KOLOM)
print(DATA)

        1                  2       3            4   5                    6  \
0      39          State-gov   77516    Bachelors  13        Never-married   
1      50   Self-emp-not-inc   83311    Bachelors  13   Married-civ-spouse   
2      38            Private  215646      HS-grad   9             Divorced   
3      53            Private  234721         11th   7   Married-civ-spouse   
4      28            Private  338409    Bachelors  13   Married-civ-spouse   
...    ..                ...     ...          ...  ..                  ...   
32556  27            Private  257302   Assoc-acdm  12   Married-civ-spouse   
32557  40            Private  154374      HS-grad   9   Married-civ-spouse   
32558  58            Private  151910      HS-grad   9              Widowed   
32559  22            Private  201490      HS-grad   9        Never-married   
32560  52       Self-emp-inc  287927      HS-grad   9   Married-civ-spouse   

                        7               8       9       10     

In [ ]:
# MENAMPILKAN 10 BARIS AWAL DATA
DATA.head(10)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K


In [ ]:
# MEMBUAT DATA FRAME
KELAS={'NOMOR':['1','2'], 'KELAS':['A','B']}
Data_Kelas=pd.DataFrame(KELAS)
print(Data_Kelas)

  NOMOR KELAS
0     1     A
1     2     B
